### ISSUE TITLE
90 seconds = 100 ticks

### ISSUE THREAD

**Issue by dogsbody** [dogsbodytech/statuspile#1]
The initial build had a 100 second countdown which we changed to 90 seconds.

However we are vuetify countdown which always runs from 100 to 0. [Relevant link](https://vuetifyjs.com/en/components/progress#rotate).

We changed the seconds to be 90 & that now means one tick on the countdown wont represent exactly 1 second but 0.9 seconds.

Not a problem but would be nice to fix at some point in the future :-)

**Comment by dhrumil4u360** [comment]
Managed to change display to run from 90 to 0. So, this is fixed now. 1 tick represents 1 second now.
