### ISSUE TITLE
Email and Telephone don't load for the provider Dogsbody Technology

### ISSUE THREAD

**Issue by ghost** [dogsbodytech/statuspile#14]
**Describe the bug**
Email and Telephone don't load for the provider Dogsbody Technology

**To Reproduce**
1. Go to https://www.statuspile.com/dashboard

**Expected behavior**
All of the providers load

**Additional context**
This issue appears to be due to them being renamed on the provider's status page to support via X

It looks like the provider needs updating in statuspile/src/views/Dashboard.vue

**Comment by dogsbody** [comment]
Fixed in #15
