### ISSUE TITLE
Add Vtex's status page

### ISSUE THREAD

**Issue by lucasayb** [dogsbodytech/statuspile#34]
I think it would be great if we had Vtex's status page in this list! 

https://status.vtex.com/

**Comment by dogsbody** [comment]
Now pushed to https://www.statuspile.com/ :+1:

**Comment by lucasayb** [comment]
@dogsbody thank you!!

**Comment by dogsbody** [comment]
@lucasayb We've seen a big increase in visitors and users for StatusPile over the last few days. May I ask where you heard of this project from please? :-)

**Comment by lucasayb** [comment]
@dogsbody that's great! I've heard from a Brazillian Youtuber that do a lot's of videos related with development and development tools.

https://www.youtube.com/watch?v=tpaSZ8x21PI

You can check on this video :)

**Comment by lucasayb** [comment]
Also, a colleague from the company where I'm working at sent to me this tool!
https://github.com/regis-samurai

**Comment by dogsbody** [comment]
@lucasayb That is awesome! Thank you :-) We would have never known that :-)
